project:
  type: website

website:
  title: "Sadashiv Nandanikar"
  
  favicon: "images/luffy.jpg"
  
  page-footer:
    center: |
      <span class="container"><strong>[Contact Sadashiv Nandanikar](mailto:nandanikar.sadashiv0712@gmail.com){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/07Sada){target="_blank"}</strong></span>
    background: "#004E4F"
    
  navbar:
    
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: Blogs.qmd
        text: Blogs
      # - href: tidytuesday.qmd
      #   text: TidyTuesday
      # - href: workshops.qmd
      #   text: Workshops
      # - href: blogs.qmd
      #   text: Blogs
        
    right:
      - icon: linkedin
        href: https://linkedin.com/in/sadashiv-nandanikar-406484292
        aria-label: Quarto LinkedIn
      - icon: github
        href: https://github.com/07Sada
        aria-label: Quarto Github
        
  search: 
    location: navbar
    type: overlay

format:
  html:
    grid: 
      body-width: 2000px
      sidebar-width: 200px
      margin-width: 200px
    theme:
      light: [cosmo, theme_light_custom.scss]
      dark: [cosmo, theme_dark_custom.scss]
    css: styles.css
    citations-hover: true
    code-link: true
    code-fold: show
    code-tools: false
    code-block-border-left: "#004E4F"
    

    
editor: visual

